console.log("my first console project");
first_name = "Vivaan";
console.log(first_name);
last_name = "Rochlani";
console.log(last_name);
full_name = first_name + last_name;
console.log(full_name);
number1 = 30;
console.log(number1);
number2 = 8;
console.log(number2);
add = number1+number2;
console.log(add);
subtract = number1-number2;
console.log(subtract);
multiply = number1*number2;
console.log(multiply);
divide = number1/number2;
console.log(divide);